repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        entry: gitleaks protect
        pass_filenames: false
        args:
          - --staged
          - --verbose
          - --redact
          - --config
          - .gitleaks.toml
          - --report-format
          - sarif
          - --report-path
          - /tmp/gitleaks.sarif
